# Generated by Django 2.1.5 on 2019-02-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_classes_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='cls',
        ),
    ]
